import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  const speed = 100;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-emerald-400">
        <header className="py-5">
          <h1 className="text-center">FAST GLAS</h1>
        </header>
        <div className="flex flex-1 items-center justify-center">
          <div>
            <div className="relative aspect-square w-96">
              <div className="absolute inset-0 translate-x-2 translate-y-2 bg-black" />
              <div className="absolute inset-0 border-4 border-black bg-white">
                {/* google here */}
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
