import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import PocketBase from "pocketbase";

const Home: NextPage = () => {
  const speed = 100;

  const pb = new PocketBase("http://127.0.0.1:8090");

  const getRecords = async () => {
    const list = await pb.collection("glasses").getList(1, 100);

    console.log(list);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-emerald-400">
        <header className="py-5">
          <h1 className="font-outline-2 text-center text-yellow-300">
            FASTGLAS
          </h1>
        </header>
        <div className="flex flex-1 flex-col items-center justify-center gap-5">
          <div className="flex items-center gap-10">
            <button
              onClick={() => getRecords()}
              className="rotate-0 scale-100 transition-all hover:-rotate-3 active:scale-95"
            >
              <img src="/assets/down.svg" />
            </button>
            <div className="relative aspect-square w-96 p-3">
              <div className="absolute inset-0 translate-x-2 translate-y-2 bg-black" />
              <div className="absolute inset-0 border-4 border-black bg-white">
                {/* google here */}
              </div>
            </div>
            <button className="rotate-0 scale-100 transition-all hover:rotate-3 active:scale-95">
              <img src="/assets/up.svg" />
            </button>
          </div>
          <p className="text-5xl font-extrabold italic">{speed} Km/h</p>
        </div>
      </main>
    </>
  );
};

export default Home;
